root:
  window:
    title: Software by Michael Arakilian
    menu: false
    geometry:
      resizable: false
      width: 650
      height: 550
    button:
      color: gray
    font:
      family: Helvetica
      size: 18
      style: bold
      color: black
