root:
  window:
    title: Software by Michael Arakilian
    menu: false
    geometry:
      resizable: false
      width: 650
      height: 550
  content:
    intro:
      title: Some title
      description: "This is the :clickable*: link to something."
      link: "https://github.com"
