root:
  title: Software by Michael Arakilian
  menu: false
  geometry:
    resizable: false
    width: 550
    height: 460
  content:
    intro:
      title:
        entry: "This is the title"
        width: 50
        height: 1
        color: black
        font:
          family: Helvetica
          size: 20
          style: bold
      description:
        entry: "This is the :clickable item*: link to something."
        link: "https://github.com"
        width: 36
        height: 1
        color: black
        font:
          family: Helvetica
          size: 14
          style: normal
    path:
      entry:
        win: C:\project
        linux: usr/local/bin
        mac: usr/local/bin
      input:
        color: black
        width: 43
        height: 2
        relief: 'sunken'
        borderwidth: 2
        font:
          family: Arial
          size: 14
          style: normal
      button:
        entry: Change
        color: white
        background: '#85877C'
        width: 8
        height: 2
        font:
          family: Arial
          size: 14
          style: normal
